// Pre-renders the React Email templates into generated/index.ts: a dependency-free module the
// Deno edge functions import. Values are substituted at send time (HTML-escaped in the HTML part).
// Run: pnpm --filter @home/emails build
import { render } from '@react-email/render'
import { writeFile } from 'node:fs/promises'
import type { ReactElement } from 'react'
import {
  InviteEmail,
  inviteSample,
  inviteSubject,
  type InviteEmailProps,
} from '../src/templates/invite.tsx'

interface TemplateDef<P> {
  fn: string
  propsType: string
  sample: P
  element: (props: P) => ReactElement
  subject: (props: P) => string
}

const templates = [
  {
    fn: 'renderInviteEmail',
    propsType: 'InviteEmailVars',
    sample: inviteSample,
    element: (props: InviteEmailProps) => <InviteEmail {...props} />,
    subject: inviteSubject,
  } satisfies TemplateDef<InviteEmailProps>,
]

// Numeric placeholders survive the plain-text renderer, which may change letter case.
const placeholder = (i: number) => `%%${i}%%`

let out = `// GENERATED by packages/emails/scripts/build.tsx. Do not edit; run \`pnpm --filter @home/emails build\`.

export interface RenderedEmail {
  subject: string
  html: string
  text: string
}

export function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

function fill(template: string, values: string[], transform: (value: string) => string): string {
  return template.replace(/%%(\\d+)%%/g, (_, i: string) => transform(values[Number(i)] ?? ''))
}

const oneLine = (value: string) => value.replace(/[\\r\\n]+/g, ' ')
const identity = (value: string) => value
`

for (const t of templates) {
  const keys = Object.keys(t.sample) as (keyof typeof t.sample)[]
  const placeholders = Object.fromEntries(
    keys.map((k, i) => [k, placeholder(i)]),
  ) as unknown as typeof t.sample

  const html = await render(t.element(placeholders))
  const text = await render(t.element(placeholders), { plainText: true })
  const subject = t.subject(placeholders)

  keys.forEach((k, i) => {
    if (!html.includes(placeholder(i))) throw new Error(`${t.fn}: "${k}" missing from HTML`)
  })

  out += `
export interface ${t.propsType} {
${keys.map((k) => `  ${k}: string`).join('\n')}
}

export function ${t.fn}(vars: ${t.propsType}): RenderedEmail {
  const values = [${keys.map((k) => `vars.${k}`).join(', ')}]
  return {
    subject: fill(${JSON.stringify(subject)}, values, oneLine),
    html: fill(${JSON.stringify(html)}, values, escapeHtml),
    text: fill(${JSON.stringify(text)}, values, identity),
  }
}
`
}

await writeFile(new URL('../generated/index.ts', import.meta.url), out)
console.log(`Rendered ${templates.length} template(s) to generated/index.ts`)
