-- Activity log: what the triggers record, who they credit, and who can read it.
begin;
select plan(28);

insert into auth.users (id, email, raw_user_meta_data) values
  ('11111111-1111-1111-1111-111111111111', 'ada@example.com', '{"full_name": "Ada Obi"}'),
  ('22222222-2222-2222-2222-222222222222', 'bola@example.com', '{"full_name": "Bola Ade"}'),
  ('33333333-3333-3333-3333-333333333333', 'chidi@example.com', '{}');

set local role authenticated;
select set_config('request.jwt.claims', '{"sub": "11111111-1111-1111-1111-111111111111", "role": "authenticated"}', true);
select set_config('test.hid', (public.create_household('Obi home')).id::text, true);
select set_config('test.cat', (
  select id::text from public.expense_categories
  where household_id = current_setting('test.hid')::uuid and name = 'Water'), true);
select set_config('test.cat2', (
  select id::text from public.expense_categories
  where household_id = current_setting('test.hid')::uuid and name = 'Fuel & Generator'), true);

-- The log in insertion order.
create temp view log as
select id, entity_type, action, summary, actor_id, changes, entity_id
from public.activity_log order by id;
grant select on log to authenticated, service_role;

select is(
  (select row(entity_type, action, summary, actor_id)::text from log),
  row('member', 'joined', 'joined the household', '11111111-1111-1111-1111-111111111111'::uuid)::text,
  'creating a household logs its creator joining'
);

-- ---------------------------------------------------------------- expenses
insert into public.expenses (household_id, amount_minor, occurred_on, category_id, description)
values (current_setting('test.hid')::uuid, 4500000, '2026-09-20', current_setting('test.cat')::uuid, 'Water tanker');
select set_config('test.eid', (select id::text from public.expenses where description = 'Water tanker'), true);

select is(
  (select row(action, summary, changes ->> 'label', actor_id)::text from log where entity_type = 'expense'),
  row('created', 'added ₦45,000', 'Water tanker', auth.uid())::text,
  'adding an expense is logged with the amount'
);

update public.expenses set amount_minor = 5400000 where id = current_setting('test.eid')::uuid;
select is(
  (select summary from log where entity_type = 'expense' and action = 'updated'),
  'edited amount ₦45,000 → ₦54,000',
  'edits describe what changed'
);
select is(
  (select changes -> 'fields' -> 'amount_minor' from log where entity_type = 'expense' and action = 'updated'),
  '[4500000, 5400000]'::jsonb,
  'and record the old and new values'
);

update public.expenses
set amount_minor = 5400050, description = 'Water tanker (big)', occurred_on = '2026-09-21',
    category_id = current_setting('test.cat2')::uuid, notes = 'Paid cash'
where id = current_setting('test.eid')::uuid;
select is(
  (select summary from log where entity_type = 'expense' and action = 'updated' order by id desc limit 1),
  'edited amount ₦54,000 → ₦54,000.50, description “Water tanker” → “Water tanker (big)”, '
    || 'date 20 Sep 2026 → 21 Sep 2026, category Water → Fuel & Generator, notes',
  'several changes are listed in one entry'
);

select set_config('test.count', (select count(*)::text from public.activity_log), true);
update public.expenses set description = description where id = current_setting('test.eid')::uuid;
select is((select count(*)::text from public.activity_log), current_setting('test.count'),
  'saving without changes logs nothing');

update public.expenses set deleted_at = now() where id = current_setting('test.eid')::uuid;
update public.expenses set deleted_at = null where id = current_setting('test.eid')::uuid;
select is(
  (select array_agg(summary order by id) from log where entity_type = 'expense' and action in ('deleted', 'restored')),
  array['deleted expense', 'restored expense'],
  'deleting and restoring are logged'
);

-- Pending bills from recurring expenses: confirming reads as such.
reset role;
select set_config('request.jwt.claims', '', true);
insert into public.expenses (household_id, amount_minor, occurred_on, category_id, description, status, paid_by)
values (current_setting('test.hid')::uuid, 1500000, '2026-09-24', current_setting('test.cat')::uuid, 'DSTV', 'pending', null);
select set_config('request.jwt.claims', '{"sub": "11111111-1111-1111-1111-111111111111", "role": "authenticated"}', true);
set local role authenticated;
select is(
  (select row(summary, actor_id)::text from log where changes ->> 'label' = 'DSTV'),
  row('added pending bill for ₦15,000', null::uuid)::text,
  'bills generated by the daily job have no actor'
);
update public.expenses set status = 'confirmed', amount_minor = 1600000 where description = 'DSTV';
select is(
  (select summary from log where changes ->> 'label' = 'DSTV' and action = 'updated'),
  'confirmed ₦16,000',
  'confirming a pending bill'
);

-- ---------------------------------------------------------------- receipts
insert into public.expense_receipts (household_id, expense_id, storage_path, file_name, mime_type, size_bytes)
values (current_setting('test.hid')::uuid, current_setting('test.eid')::uuid,
        current_setting('test.hid') || '/' || current_setting('test.eid') || '/r.jpg', 'r.jpg', 'image/jpeg', 10);
update public.expense_receipts set deleted_at = now() where file_name = 'r.jpg';
select is(
  (select array_agg(summary order by id) from log
   where entity_type = 'receipt' and changes ->> 'expense_id' = current_setting('test.eid')),
  array['added receipt r.jpg', 'deleted receipt r.jpg'],
  'receipts are logged against their expense'
);

-- ---------------------------------------------------------------- providers
insert into public.providers (household_id, name, trade) values (current_setting('test.hid')::uuid, 'Emeka Gen', 'generator_technician');
update public.providers set rating = 4 where name = 'Emeka Gen';
update public.providers set phone = '+2348051234567', area = 'Lekki' where name = 'Emeka Gen';
select is(
  (select array_agg(summary order by id) from log where entity_type = 'provider'),
  array['added provider', 'rated 4/5', 'edited phone, area'],
  'provider changes are logged'
);

-- ---------------------------------------------------------------- tasks
insert into public.tasks (household_id, title, schedule_type, frequency, start_on, next_due_on)
values (current_setting('test.hid')::uuid, 'Service generator', 'fixed', 'monthly', '2026-09-20', '2026-09-20');
select set_config('test.tid', (select id::text from public.tasks where title = 'Service generator'), true);
update public.tasks set frequency = 'quarterly', interval_count = 2, next_due_on = '2026-10-01', reminder_days_before = 3
where id = current_setting('test.tid')::uuid;
select is(
  (select summary from log where entity_type = 'task' and action = 'updated'),
  'edited schedule, due date, reminder',
  'task edits name each kind of change once'
);

select set_config('test.comp', public.complete_task(current_setting('test.tid')::uuid, '2026-10-03')::text, true);
select is(
  (select row(action, summary, changes ->> 'completion_id')::text from log
   where entity_type = 'task' order by id desc limit 1),
  row('completed', 'marked done (due 1 Oct 2026)', current_setting('test.comp'))::text,
  'completing is logged once, not as an edit of the due date'
);
select lives_ok($$ select public.undo_task_completion(current_setting('test.comp')::uuid) $$, 'undo');
select is(
  (select summary from log where entity_type = 'task' order by id desc limit 1),
  'undid “done” from 3 Oct 2026',
  'undoing is logged'
);
select is(
  (select count(*)::int from log where entity_id = current_setting('test.tid')::uuid),
  4,
  'the task history has exactly: added, edited, done, undone'
);

-- ---------------------------------------------------------------- members and invites
reset role;
set local role service_role;
select set_config('test.inv', (
  select invite_id::text from public.invite_upsert(current_setting('test.hid')::uuid, 'bola@example.com', repeat('a', 64),
                                                   '11111111-1111-1111-1111-111111111111')), true);
select lives_ok(
  $$ select public.invite_upsert(current_setting('test.hid')::uuid, 'bola@example.com', repeat('b', 64),
                                 '11111111-1111-1111-1111-111111111111') $$,
  'resend'
);
select lives_ok($$ select public.invite_accept(repeat('b', 64), '22222222-2222-2222-2222-222222222222', false) $$, 'accept');
select lives_ok($$ select * from public.invite_upsert(current_setting('test.hid')::uuid, 'chidi@example.com', repeat('c', 64),
                                                        '11111111-1111-1111-1111-111111111111') $$, 'invite chidi');
select lives_ok($$ select public.invite_revoke((select id from public.invites where email = 'chidi@example.com'),
                                              '22222222-2222-2222-2222-222222222222') $$, 'bola revokes');
select lives_ok($$ select public.leave_household(current_setting('test.hid')::uuid, '22222222-2222-2222-2222-222222222222', false) $$, 'bola leaves');

select is(
  (select array_agg(row(summary, actor_id)::text order by id) from log where entity_type in ('invite', 'member')
   and id >= (select min(id) from log where entity_type = 'invite')),
  array[
    row('invited bola@example.com', '11111111-1111-1111-1111-111111111111'::uuid)::text,
    row('resent the invite to bola@example.com', '11111111-1111-1111-1111-111111111111'::uuid)::text,
    row('joined the household', '22222222-2222-2222-2222-222222222222'::uuid)::text,
    row('invited chidi@example.com', '11111111-1111-1111-1111-111111111111'::uuid)::text,
    row('cancelled the invite to chidi@example.com', '22222222-2222-2222-2222-222222222222'::uuid)::text,
    row('left the household', '22222222-2222-2222-2222-222222222222'::uuid)::text
  ],
  'invites and membership changes credit the right person'
);

select set_config('test.link', (
  select invite_id::text from public.invite_upsert(current_setting('test.hid')::uuid, null, repeat('d', 64),
                                                   '11111111-1111-1111-1111-111111111111')), true);
select lives_ok($$ select public.invite_rotate(current_setting('test.link')::uuid, '11111111-1111-1111-1111-111111111111', repeat('e', 64)) $$, 'new link');
select lives_ok($$ select public.invite_revoke(current_setting('test.link')::uuid, '11111111-1111-1111-1111-111111111111') $$, 'cancel link');
select is(
  (select array_agg(summary order by id) from log where entity_id = current_setting('test.link')::uuid),
  array['created an invite link', 'made a new invite link', 'cancelled an invite link'],
  'invite links without an email are described as links'
);

-- ---------------------------------------------------------------- access
reset role;
set local role authenticated;
select throws_ok(
  $$ insert into public.activity_log (household_id, entity_type, entity_id, action, summary)
     values (current_setting('test.hid')::uuid, 'expense', gen_random_uuid(), 'created', 'fake') $$,
  '42501', null, 'members cannot write to the log'
);
select set_config('request.jwt.claims', '{"sub": "33333333-3333-3333-3333-333333333333", "role": "authenticated"}', true);
select is_empty($$ select 1 from public.activity_log $$, 'outsiders see no activity');

-- Deleting a household (last member leaving) doesn't trip over its own log.
reset role;
set local role service_role;
select lives_ok($$ select public.leave_household(current_setting('test.hid')::uuid, '11111111-1111-1111-1111-111111111111', true) $$,
  'the last member can delete the household');

reset role;
select * from finish();
rollback;
